### PR TITLE
Implemented a simple steps-based example

### PR DESCRIPTION
**Pull request by werner291**
Hello there!

I tried writing a simple example to document (#28) how to compose two actions together.

Documenting comments aren't quite there yet (kinda ran into my bedtime), but I did run it, and variables appear to change as they should.

Can you take a look to see if this is the kind of set-up you had in mind? I'll go through it and document stuff tomorrow.

### CODE REVIEW

**Review by zkat — COMMENTED** [review]
This is excellent! Thank you for taking the time to do this. This example is fantastic and really shows how this stuff is expected to work really clearly, imo.

If you want to add more comments, I think that's a great idea and I'll wait for that.

Also, it would be nice if you added something to the README about available examples so people know where to look.

**Comment by werner291** [comment]
@zkat There we go. Ready to merge if you are.

**Comment by werner291** [comment]
Wait, right the readme, one moment

**Comment by werner291** [comment]
There we go

**Review by zkat — APPROVED** [review]
I really like how you explained this! The example is really clear and covers the reasoning behind some important points (like cancellation, adapting to world changes, etc) really nicely.

**Pull request merged**
