### PR TITLE
3d RTS example

### PR DESCRIPTION
**Pull request by stargazing-dino**
* related to #6 

Basic working example

TODO
- [x] Add UI for money, fatigue, inventory
- [x] Documentation
- [x] Remove bevy_editor_pls

https://github.com/zkat/big-brain/assets/29642168/6fdbde1c-4c77-42f3-ac1b-2992aeab8588

(video sped up by 2x)

### CODE REVIEW

**Comment by zkat** [comment]
This looks so cool!!

**Comment by stargazing-dino** [comment]
The docs are not super thought out and might need some direction. Let me know if you want them more as a "guide" type style or simple doc/symbol comments and I can go through them again.

This should be ready to review though :D

**Review by zkat — APPROVED** [review]
ahhh this looks fantastic.

Honestly, I think the docs are good enough for now and we can add more guide-like clarifications if people ask for them, imo.

**Comment by zkat** [comment]
looks like there's a clippy issue :)

**Comment by stargazing-dino** [comment]
I think I got all the clippy issues 🧑‍🏭  . Also slightly changed some of the example's numbers so the example moves a little faster/is more visually appealing

**Pull request merged**
